Use defined marco to determine whether to use HWY_RVV_AVOID_VXRM
google/highway pull request #1540
Opened 2023-07-10 08:29 UTC by bhbruce

The origin purpose of `HWY_RVV_AVOID_VXRM` is to detect whether VXRM is embedded in an intrinsic function argument.
If not embedded into an argument, `HWY_RVV_AVOID_VXRM` is defined.

This PR changes to use a predefined macro to check to make it available for both clang & gcc.

2023-07-10 10:23 UTC, jan-wassenberg requested changes
Hi @bhbruce , thanks for suggesting this change!
Unfortunately we have __riscv_v_intrinsic = 11000 on LLVM trunk, but it still requires the new argument, so we must not define AVOID.

Is there any other way to detect this?

Perhaps one alternative would be to change the AVOID macro into a tri-state, where undefined = default (= avoid on GCC<14), 1=always avoid, 0=never avoid?

2023-07-10 12:23 UTC, jan-wassenberg commented
We could use HWY_COMPILER_CLANG (which is still correct in the case of Apple LLVM).
Is your proposal: HWY_COMPILER_CLANG || __riscv_v_intrinsic < 11000: add arg; else AVOID? I think that could work.

2023-07-11 02:09 UTC, bhbruce commented
> Is your proposal: HWY_COMPILER_CLANG || __riscv_v_intrinsic < 11000: add arg; else AVOID? I think that could work.
I am not sure highway library support v0.10 intrinsic or not.

My proposal may look like this one.
```
#if HWY_COMPILER_CLANG == 1600 && __riscv_v_intrinsic == 11000 
    #define HWY_RVV_AVOID_VXRM
#elif HWY_COMPILER_GCC_ACTUAL && HWY_COMPILER_GCC_ACTUAL < 1400
    #define HWY_RVV_AVOID_VXRM
#end
```

2023-07-11 12:36 UTC, jan-wassenberg commented
Sorry to go back and forth :) There is still an issue because LLVM trunk is detected as 1600, and has intrinsic version 11000, and requires AVOID not to be set.
What we can do is AVOID on earlier clang than 1600, or intrinsics < 11000, and keep the same logic you have for GCC.
I'll send a change for this :)

2023-07-11 12:57 UTC, closed without merging